import { WeeklyMarketingReport } from "./weekly-marketing-types";

export const INITIAL_WEEKLY_MARKETING_REPORTS: WeeklyMarketingReport[] = [
  // WEEK 41: Current week (05/10/2026 – 11/10/2026) - In Progress / Draft
  {
    reportId: "rep-2026-w41",
    weekNumber: 41,
    year: 2026,
    startDate: "2026-10-05",
    endDate: "2026-10-11",
    createdBy: "Ngô Gia Bảo",
    createdAt: "2026-10-06T09:00:00+07:00",
    updatedAt: "2026-10-07T14:30:00+07:00",
    status: "draft",

    tiktokMetrics: {
      followersStart: 34200,
      followersEnd: 36150,
      newFollowers: 1950,
      videosPublished: 6,
      totalViews: 215400,
      uniqueReach: 154000,
      profileViews: 11200,
      likes: 12800,
      comments: 940,
      shares: 1120,
      saves: 850,
      bestVideoTitle: "Bàn giao lô 5 Mooc Ben Tải Nặng Hatico về mỏ đá Ninh Bình",
      bestVideoViews: 86400,
      bestVideoEngagement: 6240,
      leads: 32,
      notes: "Series video thực tế tại bãi xe và kho Ninh Bình tạo độ tin cậy rất cao cho cánh tài xế.",
      adSpend: 3800000,
      adImpressions: 98000,
      adReach: 74000,
      adClicks: 2680,
      adLeads: 14,
      adConversions: 2,
    },

    facebookMetrics: {
      followersStart: 42800,
      followersEnd: 43650,
      newFollowers: 850,
      postsPublished: 8,
      reach: 92400,
      impressions: 148000,
      pageViews: 6850,
      postEngagements: 7850,
      likes: 4620,
      comments: 630,
      shares: 340,
      linkClicks: 2260,
      messagesStarted: 78,
      leads: 46,
      qualifiedLeads: 24,
      conversions: 5,
      bestPostTitle: "So sánh thực tế: Mooc Xương CIMC 3 trục vs Mooc Cổ Cò 40 feet",
      adSpend: 11400000,
      adReach: 86000,
      adImpressions: 165000,
      adFrequency: 1.92,
      adLinkClicks: 3420,
      adLeads: 36,
      adConversions: 4,
    },

    websiteMetrics: {
      totalUsers: 14200,
      newUsers: 10800,
      sessions: 19800,
      pageViews: 48600,
      avgSessionDurationSeconds: 154, // 2m 34s
      bounceRate: 38.6,
      engagementRate: 61.4,
      trafficOrganicSearch: 8200,
      trafficFacebook: 4600,
      trafficTiktok: 3900,
      trafficDirect: 2100,
      trafficReferral: 1000,
      contactFormSubmissions: 28,
      phoneCallClicks: 42,
      zaloClicks: 65,
      quoteRequests: 34,
      leads: 40,
      qualifiedLeads: 22,
      conversions: 4,
      topLandingPages: [
        { path: "/san-pham/mooc-ben", title: "Sơ mi rơ mooc ben tự đổ Hatico", views: 14200, leads: 16 },
        { path: "/san-pham/mooc-xuong-cimc", title: "Mooc xương CIMC 3 trục 40ft", views: 11300, leads: 12 },
        { path: "/bang-gia-so-mi-ro-mooc-2026", title: "Bảng giá sơ mi rơ mooc mới nhất 2026", views: 9800, leads: 8 },
        { path: "/san-pham/mooc-long-khung-mui", title: "Mooc lồng khung mui bạt cao cấp", views: 6400, leads: 3 },
        { path: "/khuyen-mai-thang-10", title: "Ưu đãi tặng lốp & hỗ trợ đăng kiểm", views: 4200, leads: 1 },
      ],
      topTrafficSources: [
        { source: "Google Organic (SEO)", sessions: 8200, leads: 18 },
        { source: "Facebook Ads & Page", sessions: 4600, leads: 12 },
        { source: "TikTok Video Link", sessions: 3900, leads: 6 },
        { source: "Direct (hatico.vn)", sessions: 2100, leads: 3 },
        { source: "Zalo OA & Nhóm xe", sessions: 1000, leads: 1 },
      ],
      bestPerformingPage: "/san-pham/mooc-ben",
    },

    leadMetrics: {
      totalLeads: 118,
      newLeads: 96,
      qualifiedLeads: 54,
      customersContacted: 112,
      quoteRequests: 68,
      quotationsSent: 61,
      convertedCustomers: 11,
      revenueGenerated: 4250000000, // 4.25 tỷ VND
      channelBreakdown: [
        { source: "Facebook Ads", leads: 36, qualifiedLeads: 18, conversions: 4, adSpend: 11400000 },
        { source: "TikTok Organic", leads: 18, qualifiedLeads: 9, conversions: 2, adSpend: 0 },
        { source: "TikTok Ads", leads: 14, qualifiedLeads: 6, conversions: 1, adSpend: 3800000 },
        { source: "Website SEO Organic", leads: 18, qualifiedLeads: 10, conversions: 2, adSpend: 0 },
        { source: "Website Hotline & Zalo", leads: 22, qualifiedLeads: 9, conversions: 2, adSpend: 0 },
        { source: "Facebook Organic", leads: 10, qualifiedLeads: 5, conversions: 1, adSpend: 0 },
        { source: "Giới thiệu (Referral)", leads: 6, qualifiedLeads: 4, conversions: 1, adSpend: 0 },
        { source: "Khác", leads: 2, qualifiedLeads: 1, conversions: 0, adSpend: 0 },
      ],
    },

    contentPerformance: [
      {
        id: "cnt-41-1",
        platform: "TikTok",
        title: "Bàn giao lô 5 Mooc Ben Tải Nặng Hatico về mỏ đá Ninh Bình",
        publishDate: "2026-10-05",
        contentType: "Video ngắn",
        viewsOrReach: 86400,
        likes: 5420,
        comments: 420,
        shares: 510,
        leads: 18,
        status: "Xuất sắc",
        rank: 1,
      },
      {
        id: "cnt-41-2",
        platform: "Facebook",
        title: "So sánh thực tế: Mooc Xương CIMC 3 trục vs Mooc Cổ Cò 40 feet",
        publishDate: "2026-10-06",
        contentType: "Hình ảnh & Infographic",
        viewsOrReach: 48200,
        likes: 2180,
        comments: 310,
        shares: 185,
        leads: 14,
        status: "Xuất sắc",
        rank: 2,
      },
      {
        id: "cnt-41-3",
        platform: "Website",
        title: "Bảng giá sơ mi rơ mooc mới nhất quý 4/2026 và thủ tục vay góp",
        publishDate: "2026-10-05",
        contentType: "Bài viết SEO",
        viewsOrReach: 9800,
        likes: 340,
        comments: 65,
        shares: 82,
        leads: 12,
        status: "Tốt",
        rank: 3,
      },
      {
        id: "cnt-41-4",
        platform: "TikTok",
        title: "Quy trình kiểm tra chân chống Fuwa & hệ thống phanh Wabco trước khi giao",
        publishDate: "2026-10-06",
        contentType: "Video kỹ thuật",
        viewsOrReach: 41200,
        likes: 2450,
        comments: 180,
        shares: 210,
        leads: 6,
        status: "Tốt",
      },
      {
        id: "cnt-41-5",
        platform: "Facebook",
        title: "Chính sách bảo hành 2 năm cho dầm chính và trục mooc tại Hatico",
        publishDate: "2026-10-07",
        contentType: "Bài viết hình ảnh",
        viewsOrReach: 24600,
        likes: 1200,
        comments: 85,
        shares: 42,
        leads: 4,
        status: "Trung bình",
      },
    ],

    weeklyAnalysis: {
      highlights: [
        "Lượng tiếp cận tuần này đạt 268.5k người (+9.2%), số leads toàn kênh đạt 118 khách (+13.5% so với tuần 40).",
        "Video bàn giao xe thực tế trên TikTok tạo hiệu ứng lan tỏa mạnh, kéo theo 18 leads trực tiếp hỏi giá mooc ben.",
        "Chi phí trên 1 Lead (CPL) từ Facebook Ads giảm từ 145.000 đ xuống 132.000 đ nhờ tối ưu tệp đối tượng doanh nghiệp logistics và bến bãi.",
        "Bộ phận kinh doanh đã chốt hợp đồng thành công 11 sơ mi rơ mooc, mang về doanh thu ước tính 4.25 tỷ đồng.",
      ],
      bestContentRationale:
        "Video 'Bàn giao lô 5 Mooc Ben Hatico về Ninh Bình' hiệu quả nhất vì đánh trúng tâm lý người mua vận tải: thích xem hình ảnh giao xe thật, xem độ dày thép thùng và nghe tiếng ben lên xuống chân thực. Giọng thuyết minh kỹ thuật rõ ràng, không hoa mỹ.",
      issuesAndImprovements: [
        "Tỷ lệ phản hồi tin nhắn Facebook ngoài giờ hành chính (sau 19h) còn chậm trung bình 28 phút, làm rớt khoảng 4 khách hỏi giá gấp.",
        "Landing page '/san-pham/mooc-long-khung-mui' tỷ lệ thoát còn cao (48%), cần bổ sung thêm bảng thông số kỹ thuật chi tiết và video quay cận cảnh chốt khóa bạt.",
        "Nội dung YouTube Shorts chưa triển khai đồng bộ, đang bỏ lỡ lượng tìm kiếm trên nền tảng video dài.",
      ],
      nextWeekPlan: [
        "Sản xuất chùm 3 video chuyên sâu: 'Cảnh báo 5 điểm yếu trên mooc ben trôi nổi thị trường' và 'Cách chọn trục Jost chuẩn'.",
        "Triển khai kịch bản Auto-Chatbot trực hotline và fanpage 24/7 để giữ chân khách hỏi mua lúc đêm muộn.",
        "Tăng ngân sách chiến dịch Facebook Ads cho dòng Mooc Cổ Cò Hải Phòng lên thêm 15% để đón sóng vận chuyển hàng cảng cuối năm.",
        "Gửi bản báo giá định kỳ qua Zalo OA cho tệp 180 khách hàng cũ từng mua xe năm 2025.",
      ],
      recommendations: [
        "Đề xuất phòng Kinh doanh cử 1 nhân sự phối hợp quay video thực tế mỗi khi có lễ bàn giao xe lớn tại cảng Hải Phòng và bãi Hà Nội.",
        "Xin phê duyệt ngân sách chạy thử nghiệm kênh Google Search Ads cho cụm từ khóa 'mua mooc ben hà nội', dự kiến 3.000.000 đ/tuần.",
      ],
    },
  },

  // WEEK 40: (28/09/2026 – 04/10/2026) - Submitted & Approved
  {
    reportId: "rep-2026-w40",
    weekNumber: 40,
    year: 2026,
    startDate: "2026-09-28",
    endDate: "2026-10-04",
    createdBy: "Ngô Gia Bảo",
    createdAt: "2026-09-29T08:30:00+07:00",
    updatedAt: "2026-10-05T09:15:00+07:00",
    submittedAt: "2026-10-05T09:30:00+07:00",
    approvedAt: "2026-10-05T11:00:00+07:00",
    approvedBy: "Ban Giám Đốc",
    status: "approved",

    tiktokMetrics: {
      followersStart: 32500,
      followersEnd: 34200,
      newFollowers: 1700,
      videosPublished: 5,
      totalViews: 198000,
      uniqueReach: 141000,
      profileViews: 9800,
      likes: 11200,
      comments: 780,
      shares: 940,
      saves: 720,
      bestVideoTitle: "Cận cảnh Mooc Cổ Cò 45 feet chở container lạnh",
      bestVideoViews: 74200,
      bestVideoEngagement: 5120,
      leads: 26,
      notes: "Nội dung so sánh kích thước và độ chịu lực thu hút nhiều chủ xe chạy tuyến Bắc - Nam.",
      adSpend: 3500000,
      adImpressions: 89000,
      adReach: 68000,
      adClicks: 2350,
      adLeads: 11,
      adConversions: 1,
    },

    facebookMetrics: {
      followersStart: 41900,
      followersEnd: 42800,
      newFollowers: 900,
      postsPublished: 7,
      reach: 84500,
      impressions: 136000,
      pageViews: 6100,
      postEngagements: 6920,
      likes: 4100,
      comments: 540,
      shares: 280,
      linkClicks: 2000,
      messagesStarted: 66,
      leads: 42,
      qualifiedLeads: 21,
      conversions: 4,
      bestPostTitle: "Hatico bàn giao cặp Mooc Lồng 14m cho đoàn xe Tây Bắc",
      adSpend: 11000000,
      adReach: 81000,
      adImpressions: 154000,
      adFrequency: 1.9,
      adLinkClicks: 3120,
      adLeads: 33,
      adConversions: 3,
    },

    websiteMetrics: {
      totalUsers: 12800,
      newUsers: 9600,
      sessions: 17900,
      pageViews: 43200,
      avgSessionDurationSeconds: 148,
      bounceRate: 40.2,
      engagementRate: 59.8,
      trafficOrganicSearch: 7400,
      trafficFacebook: 4200,
      trafficTiktok: 3400,
      trafficDirect: 1900,
      trafficReferral: 1000,
      contactFormSubmissions: 24,
      phoneCallClicks: 38,
      zaloClicks: 56,
      quoteRequests: 29,
      leads: 36,
      qualifiedLeads: 19,
      conversions: 4,
      topLandingPages: [
        { path: "/san-pham/mooc-ben", title: "Sơ mi rơ mooc ben tự đổ Hatico", views: 12400, leads: 14 },
        { path: "/san-pham/mooc-xuong-cimc", title: "Mooc xương CIMC 3 trục 40ft", views: 9800, leads: 10 },
        { path: "/bang-gia-so-mi-ro-mooc-2026", title: "Bảng giá sơ mi rơ mooc mới nhất 2026", views: 8900, leads: 7 },
        { path: "/san-pham/mooc-co-co", title: "Mooc cổ cò 40ft, 45ft chở container lạnh", views: 5600, leads: 4 },
        { path: "/gioi-thieu", title: "Về công ty Cổ phần XNK Quốc tế Hatico", views: 3200, leads: 1 },
      ],
      topTrafficSources: [
        { source: "Google Organic (SEO)", sessions: 7400, leads: 16 },
        { source: "Facebook Ads & Page", sessions: 4200, leads: 11 },
        { source: "TikTok Video Link", sessions: 3400, leads: 5 },
        { source: "Direct (hatico.vn)", sessions: 1900, leads: 3 },
        { source: "Zalo OA & Nhóm xe", sessions: 1000, leads: 1 },
      ],
      bestPerformingPage: "/san-pham/mooc-ben",
    },

    leadMetrics: {
      totalLeads: 104,
      newLeads: 86,
      qualifiedLeads: 46,
      customersContacted: 98,
      quoteRequests: 58,
      quotationsSent: 52,
      convertedCustomers: 9,
      revenueGenerated: 3480000000, // 3.48 tỷ VND
      channelBreakdown: [
        { source: "Facebook Ads", leads: 33, qualifiedLeads: 16, conversions: 3, adSpend: 11000000 },
        { source: "TikTok Organic", leads: 15, qualifiedLeads: 7, conversions: 1, adSpend: 0 },
        { source: "TikTok Ads", leads: 11, qualifiedLeads: 4, conversions: 1, adSpend: 3500000 },
        { source: "Website SEO Organic", leads: 16, qualifiedLeads: 9, conversions: 2, adSpend: 0 },
        { source: "Website Hotline & Zalo", leads: 18, qualifiedLeads: 8, conversions: 1, adSpend: 0 },
        { source: "Facebook Organic", leads: 9, qualifiedLeads: 4, conversions: 1, adSpend: 0 },
        { source: "Giới thiệu (Referral)", leads: 5, qualifiedLeads: 3, conversions: 1, adSpend: 0 },
        { source: "Khác", leads: 2, qualifiedLeads: 1, conversions: 0, adSpend: 0 },
      ],
    },

    contentPerformance: [
      {
        id: "cnt-40-1",
        platform: "TikTok",
        title: "Cận cảnh Mooc Cổ Cò 45 feet chở container lạnh xuất cảng",
        publishDate: "2026-09-29",
        contentType: "Video ngắn",
        viewsOrReach: 74200,
        likes: 4850,
        comments: 340,
        shares: 420,
        leads: 15,
        status: "Xuất sắc",
        rank: 1,
      },
      {
        id: "cnt-40-2",
        platform: "Facebook",
        title: "Hatico bàn giao cặp Mooc Lồng 14m cho đoàn xe Tây Bắc",
        publishDate: "2026-09-30",
        contentType: "Hình ảnh bàn giao",
        viewsOrReach: 42100,
        likes: 1980,
        comments: 260,
        shares: 140,
        leads: 12,
        status: "Xuất sắc",
        rank: 2,
      },
      {
        id: "cnt-40-3",
        platform: "Website",
        title: "Top 3 mẫu sơ mi rơ mooc ben đáng mua nhất năm 2026",
        publishDate: "2026-10-01",
        contentType: "Bài viết SEO",
        viewsOrReach: 8900,
        likes: 290,
        comments: 48,
        shares: 62,
        leads: 9,
        status: "Tốt",
        rank: 3,
      },
    ],

    weeklyAnalysis: {
      highlights: [
        "Tổng tiếp cận tuần 40 đạt 245.8k người (+18.4% so với tuần 39), hoàn thành vượt chỉ tiêu tuần.",
        "Tổng chi phí quảng cáo 14.500.000 đ mang về 44 leads quảng cáo trả phí, CPL trung bình đạt 139.400 đ/lead.",
        "Kênh kinh doanh chốt thành công 9 hợp đồng mooc với tổng giá trị 3.48 tỷ đồng.",
      ],
      bestContentRationale:
        "Video Mooc Cổ Cò giải quyết đúng nhu cầu chạy hàng lạnh xuất khẩu cuối năm từ các cửa khẩu Lạng Sơn, Móng Cái về Hải Phòng.",
      issuesAndImprovements: [
        "Một số clip TikTok quay ở bãi bị tạp âm tiếng gió và còi xe, cần trang bị micro lọc ồn gắn cổ áo.",
        "Thiếu hình ảnh chất lượng cao của kho phụ tùng chính hãng (mâm xoay, chân chống, nhíp lá).",
      ],
      nextWeekPlan: [
        "Đẩy mạnh video bàn giao mooc ben tại các mỏ đá Hà Nam và Ninh Bình.",
        "Thiết kế lại ảnh bìa Fanpage và danh mục sản phẩm chuẩn SEO cho website.",
      ],
      recommendations: [
        "Duy trì ngân sách Facebook Ads ở mức 11-12 triệu/tuần và tối ưu tiếp cận cho thị trường miền Trung.",
      ],
    },
  },

  // WEEK 39: (21/09/2026 – 27/09/2026) - Submitted & Approved
  {
    reportId: "rep-2026-w39",
    weekNumber: 39,
    year: 2026,
    startDate: "2026-09-21",
    endDate: "2026-09-27",
    createdBy: "Ngô Gia Bảo",
    createdAt: "2026-09-22T09:00:00+07:00",
    updatedAt: "2026-09-28T09:30:00+07:00",
    submittedAt: "2026-09-28T09:45:00+07:00",
    approvedAt: "2026-09-28T10:30:00+07:00",
    approvedBy: "Ban Giám Đốc",
    status: "approved",

    tiktokMetrics: {
      followersStart: 31000,
      followersEnd: 32500,
      newFollowers: 1500,
      videosPublished: 4,
      totalViews: 165000,
      uniqueReach: 120000,
      profileViews: 8200,
      likes: 9500,
      comments: 620,
      shares: 750,
      saves: 580,
      bestVideoTitle: "Thử tải mooc sàn 3 trục chở thép cuộn 45 tấn",
      bestVideoViews: 61000,
      bestVideoEngagement: 4200,
      leads: 20,
      notes: "Video thử tải tạo sự thảo luận sôi nổi về độ võng và độ đầm của dầm xe.",
      adSpend: 3200000,
      adImpressions: 78000,
      adReach: 60000,
      adClicks: 2100,
      adLeads: 9,
      adConversions: 1,
    },

    facebookMetrics: {
      followersStart: 41200,
      followersEnd: 41900,
      newFollowers: 700,
      postsPublished: 6,
      reach: 72000,
      impressions: 118000,
      pageViews: 5400,
      postEngagements: 5800,
      likes: 3400,
      comments: 420,
      shares: 210,
      linkClicks: 1750,
      messagesStarted: 54,
      leads: 35,
      qualifiedLeads: 18,
      conversions: 3,
      bestPostTitle: "Tại sao tài xế đường dài luôn chọn mooc có lốp Double Coin?",
      adSpend: 10000000,
      adReach: 74000,
      adImpressions: 138000,
      adFrequency: 1.86,
      adLinkClicks: 2800,
      adLeads: 29,
      adConversions: 2,
    },

    websiteMetrics: {
      totalUsers: 11200,
      newUsers: 8400,
      sessions: 15600,
      pageViews: 38200,
      avgSessionDurationSeconds: 142,
      bounceRate: 41.5,
      engagementRate: 58.5,
      trafficOrganicSearch: 6500,
      trafficFacebook: 3700,
      trafficTiktok: 2900,
      trafficDirect: 1600,
      trafficReferral: 900,
      contactFormSubmissions: 20,
      phoneCallClicks: 32,
      zaloClicks: 48,
      quoteRequests: 24,
      leads: 33,
      qualifiedLeads: 16,
      conversions: 3,
      topLandingPages: [
        { path: "/san-pham/mooc-ben", title: "Sơ mi rơ mooc ben tự đổ Hatico", views: 10800, leads: 12 },
        { path: "/san-pham/mooc-xuong-cimc", title: "Mooc xương CIMC 3 trục 40ft", views: 8600, leads: 9 },
        { path: "/bang-gia-so-mi-ro-mooc-2026", title: "Bảng giá sơ mi rơ mooc mới nhất 2026", views: 7800, leads: 6 },
        { path: "/san-pham/mooc-san", title: "Mooc sàn 40ft chở hàng nặng", views: 4900, leads: 3 },
        { path: "/lien-he", title: "Liên hệ bãi xe Hatico Hà Nội - Hải Phòng", views: 2800, leads: 1 },
      ],
      topTrafficSources: [
        { source: "Google Organic (SEO)", sessions: 6500, leads: 14 },
        { source: "Facebook Ads & Page", sessions: 3700, leads: 10 },
        { source: "TikTok Video Link", sessions: 2900, leads: 4 },
        { source: "Direct (hatico.vn)", sessions: 1600, leads: 3 },
        { source: "Zalo OA & Khác", sessions: 900, leads: 1 },
      ],
      bestPerformingPage: "/san-pham/mooc-ben",
    },

    leadMetrics: {
      totalLeads: 88,
      newLeads: 74,
      qualifiedLeads: 40,
      customersContacted: 82,
      quoteRequests: 48,
      quotationsSent: 44,
      convertedCustomers: 7,
      revenueGenerated: 2750000000,
      channelBreakdown: [
        { source: "Facebook Ads", leads: 29, qualifiedLeads: 14, conversions: 2, adSpend: 10000000 },
        { source: "TikTok Organic", leads: 12, qualifiedLeads: 6, conversions: 1, adSpend: 0 },
        { source: "TikTok Ads", leads: 9, qualifiedLeads: 3, conversions: 1, adSpend: 3200000 },
        { source: "Website SEO Organic", leads: 14, qualifiedLeads: 8, conversions: 1, adSpend: 0 },
        { source: "Website Hotline & Zalo", leads: 14, qualifiedLeads: 6, conversions: 1, adSpend: 0 },
        { source: "Facebook Organic", leads: 6, qualifiedLeads: 3, conversions: 1, adSpend: 0 },
        { source: "Giới thiệu (Referral)", leads: 4, qualifiedLeads: 2, conversions: 1, adSpend: 0 },
      ],
    },

    contentPerformance: [
      {
        id: "cnt-39-1",
        platform: "TikTok",
        title: "Thử tải mooc sàn 3 trục chở thép cuộn 45 tấn trên đèo",
        publishDate: "2026-09-22",
        contentType: "Video ngắn",
        viewsOrReach: 61000,
        likes: 3800,
        comments: 290,
        shares: 310,
        leads: 12,
        status: "Xuất sắc",
        rank: 1,
      },
      {
        id: "cnt-39-2",
        platform: "Facebook",
        title: "Tại sao tài xế đường dài luôn chọn mooc trang bị lốp Double Coin?",
        publishDate: "2026-09-24",
        contentType: "Bài viết kỹ thuật",
        viewsOrReach: 36000,
        likes: 1650,
        comments: 210,
        shares: 95,
        leads: 9,
        status: "Tốt",
        rank: 2,
      },
    ],

    weeklyAnalysis: {
      highlights: [
        "Lượng tương tác tăng 18% so với tuần 38 nhờ video thử tải mooc sàn chở thép.",
        "Duy trì ổn định 88 leads/tuần với tỷ lệ chuyển đổi đạt 7 khách chốt cọc mua mooc.",
      ],
      bestContentRationale:
        "Hình ảnh xe chở hàng nặng thực tế luôn tạo độ tin cậy tuyệt đối so với ảnh chụp bãi tĩnh.",
      issuesAndImprovements: [
        "Quảng cáo TikTok Ads chi phí ra click còn cao, cần đổi video thumbnail bắt mắt hơn.",
      ],
      nextWeekPlan: [
        "Quay video cận cảnh dòng mooc cổ cò chuyên chở hàng lạnh.",
      ],
      recommendations: [
        "Bổ sung chính sách tặng 1 lần bảo dưỡng miễn phí cho khách mua xe trong tháng 10.",
      ],
    },
  },
];
